- devops/aws-codebuild/Jenkinsfile.cd
- devops/aws-codebuild/Jenkinsfile.ci
Signed-off-by: Andrey Kononykhin <andkononykhin@gmail.com>
> set version of jenkins shared lib to v0.2.0-aws-codebuild

- devops/build-scripts/xenial/Pool_Party/Dockerfile
- sovtoken/setup.py
Signed-off-by: Brent <brent.zundel@gmail.com>
pin to stable indy-plenum 1.6.51 in setup.py
and to current stable versions in the Dockerfile for building a pool of nodes with the plugin
> pin to stable artifacts

- docs/transaction_whitelist.md
- sovtokenfees/sovtokenfees/messages/fields.py
- sovtokenfees/sovtokenfees/test/test_set_get_fees.py
> TOK-451 Add whitelist of transactions for SET_FEES

- sovtoken/sovtoken/test/helpers/helper_general.py
- sovtoken/sovtoken/test/helpers/helper_request.py
- sovtoken/sovtoken/test/helpers/helper_wallet.py
- sovtoken/sovtoken/test/test_public_mint.py
- sovtoken/sovtoken/test/test_public_xfer_1.py
- sovtokenfees/sovtokenfees/test/test_fees_non_xfer_txn.py
- sovtokenfees/sovtokenfees/test/test_fees_xfer_txn.py
- sovtokenfees/sovtokenfees/test/test_set_get_fees.py
Signed-off-by: dastardlychimp <darien.hess@evernym.com>
> Add a few transfer and fees tests.

- sovtoken/sovtoken/test/test_public_mint.py
Signed-off-by: dastardlychimp <darien.hess@evernym.com>
> TOK-442 Add test for repeated mint.

- sovtoken/sovtoken/messages/txn_validator.py
- sovtoken/sovtoken/test/test_public_mint.py
- sovtoken/sovtoken/test/test_public_xfer_1.py
- sovtokenfees/sovtokenfees/test/helpers/helper_request.py
- sovtokenfees/sovtokenfees/test/test_fees_non_xfer_txn.py
- sovtokenfees/sovtokenfees/test/test_fees_xfer_txn.py
Signed-off-by: dastardlychimp <darien.hess@evernym.com>
> TOK-460 Add tests for outputs with zero tokens.

- devops/aws-codebuild/Jenkinsfile.cd
Signed-off-by: Andrey Kononykhin <andkononykhin@gmail.com>
> Sets debian package version equal to source for stable CD pipeline

- sovtoken/sovtoken/exceptions.py
- sovtoken/sovtoken/test/test_token_req_handler.py
- sovtoken/sovtoken/token_req_handler.py
> Fix assertion

- devops/Makefile
- devops/build-scripts/xenial/Pool_Party/Dockerfile
- devops/denv/Dockerfile
- devops/vagrant/desktop/scripts/setup.sh
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> RC 0.9.7: New release to support new plenum

- devops/docker/ci/xenial/Dockerfile
- devops/ext/docker/base/xenial/Dockerfile.0.2.0
> [Fix rpm install] add rake into gem install

- devops/Makefile
- devops/docker/ci/xenial/Dockerfile
- devops/ext/docker/base/xenial/Dockerfile.0.2.0
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/setup.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [RC-0.9.9] bump plenum and python3-indy versions

- devops/denv/Dockerfile
- sovtoken/setup.py
- sovtoken/sovtoken/test/test_token_req_handler.py
- sovtoken/sovtoken/token_req_handler.py
- sovtokenfees/sovtokenfees/test/helper.py
- sovtokenfees/sovtokenfees/test/test_three_phase_commit.py
- sovtokenfees/sovtokenfees/test/three_phase_commit_helper.py
- Support a new interface of handlers after audit ledger is added
- Fixes in tests
- Simplification of tests
> INDY-1944: support new interface

- devops/aws-codebuild/Jenkinsfile.cd
- devops/aws-codebuild/Jenkinsfile.ci
Signed-off-by: Felippe Burk <felippe.burk@evernym.com>
> fixes to pipeline

- sovtokenfees/sovtokenfees/test/catchup/test_revert_xfer_and_other_txn_before_catchup.py
- sovtokenfees/sovtokenfees/test/catchup/test_revert_xfer_with_fees_before_catchup.py
- sovtokenfees/sovtokenfees/test/catchup/test_revert_xfer_without_fees_before_catchup.py
> [SKIP_TEST] skip tests because of st-534

- sovtoken/setup.py
- sovtoken/sovtoken/test/test_utxo_cache.py
- sovtokenfees/sovtokenfees/test/3pc_batching/test_malicious_primary_sent_pp.py
> [ST-511] fix onBatchCreated method

- sovtoken/sovtoken/main.py
- sovtoken/sovtoken/token_req_handler.py
- sovtokenfees/sovtokenfees/main.py
- sovtokenfees/sovtokenfees/static_fee_req_handler.py
- sovtokenfees/sovtokenfees/test/3pc_batching/conftest.py
- sovtokenfees/sovtokenfees/test/3pc_batching/test_malicious_primary_sent_pp_with_xfer.py
- sovtokenfees/sovtokenfees/test/catchup/revert/test_revert_xfer_and_other_txn_before_catchup.py
- sovtokenfees/sovtokenfees/test/catchup/revert/test_revert_xfer_before_catchup.py
- sovtokenfees/sovtokenfees/test/catchup/test_first_catchup_for_a_new_node.py
- sovtokenfees/sovtokenfees/test/catchup/test_tracker_after_catchup.py
- sovtokenfees/sovtokenfees/test/view_change/test_vc_reverting_different_batches.py
> [ST-534] Fix reverting logic and unskip tests

- devops/Makefile
- sovtoken/setup.py
- sovtokenfees/sovtokenfees/client_authnr.py
- sovtokenfees/sovtokenfees/test/helpers/helper_request.py
- sovtokenfees/sovtokenfees/test/test_client_authnr.py
- sovtokenfees/sovtokenfees/test/test_fees_non_xfer_txn.py
> [FIX_SIG_VERIFY] change digest to payload_digest

- devops/Makefile
- devops/denv/Dockerfile
- devops/vagrant/desktop/scripts/setup.sh
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [Rc 0.9.11] Release candidate with indy-node 1.7.1

- sovtoken/sovtoken/main.py
- sovtoken/sovtoken/token_req_handler.py
- sovtokenfees/sovtokenfees/fees_authorizer.py
- sovtokenfees/sovtokenfees/main.py
- sovtokenfees/sovtokenfees/static_fee_req_handler.py
- sovtokenfees/sovtokenfees/test/helpers/helper_node.py
- sovtokenfees/sovtokenfees/test/test_static_fee_req_handler.py
> ST-531 Migrate fees onto the Auth rules [WIP]

- sovtokenfees/sovtokenfees/static_fee_req_handler.py
- sovtokenfees/sovtokenfees/test/auth_map/test_auth_rule_validation.py
- sovtokenfees/sovtokenfees/test/dynamic_validation/test_nym_with_big_fees.py
- sovtokenfees/sovtokenfees/test/dynamic_validation/test_nym_without_fees_but_required.py
> [ST-572] Add additional validation for auth_rule requests

- sovtoken/doc/Interface/auth_rules.md
- sovtokenfees/doc/Interface/README.md
- sovtokenfees/doc/Interface/auth_rules.md
> [ST-546] add instructions for setting fees

- devops/Makefile
- devops/aws-codebuild/Jenkinsfile.cd
- devops/aws-codebuild/Jenkinsfile.ci
- devops/aws-codebuild/buildspec.yml
- sovtoken/setup.py
- sovtoken/sovtoken/test/auth_map/test_auth_mint.py
- sovtoken/sovtoken/test/auth_map/test_auth_xfer.py
- sovtokenfees/sovtokenfees/test/auth_map/test_auth_rule_validation.py
- sovtokenfees/sovtokenfees/test/auth_map/test_auth_rules.py
- sovtokenfees/sovtokenfees/test/auth_map/test_auth_set_fees.py
- sovtokenfees/sovtokenfees/test/dynamic_validation/test_nym_with_big_fees.py
- sovtokenfees/sovtokenfees/test/dynamic_validation/test_nym_without_fees_but_required.py
- sovtokenfees/sovtokenfees/test/dynamic_validation/test_valid_nym_with_fees.py
- sovtokenfees/sovtokenfees/test/dynamic_validation/test_validation_with_zero_fees.py
- sovtokenfees/sovtokenfees/test/test_get_auth_rule.py
> [BUMP_INDY] bump indy-node version

- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [BUMP_VERSION] bump version for master

- devops/Makefile
- sovtoken/setup.py
> [BUMP_NODE] bump indy-node version

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
Indy-node to 1.9.0~dev985
sovtoken to 0.9.13
sovtokenfees to 0.9.13
> Bump indy-node and plugins version.

- devops/Makefile
- devops/docker/ci/xenial/Dockerfile
- sovtoken/setup.py
- sovtokenfees/setup.py
> INDY-2083: Bump indy-node version

- devops/Makefile
- sovtoken/setup.py
Signed-off-by: ArtObr <artemobruchnikov@gmail.com>
> Bump indy-node 1011

- devops/Makefile
- sovtoken/setup.py
Signed-off-by: ArtObr <artemobruchnikov@gmail.com>
> Bump node 1014

- sovtoken/sovtoken/request_handlers/write_request_handler/xfer_handler.py
- sovtoken/sovtoken/test/test_public_xfer_1.py
Signed-off-by: ArtObr <artemobruchnikov@gmail.com>
> Fix for xfer txn

- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> ST-550: RC 1.0.0

- devops/Makefile
- sovtoken/setup.py
> ST-550: Stable 1.0.0

- devops/Makefile
- sovtoken/setup.py
> INDY-2173: bump indy-node

- devops/Makefile
- sovtoken/setup.py
> ST-609: Stable 1.0.1

- sovtoken/setup.py
- sovtoken/sovtoken/test/helpers/helper_request.py
- sovtoken/sovtoken/test/test_get_utxo_state_proof.py
> ST-602 -- Finish tests

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> Bump plugins, node and plenum versions

- devops/Makefile
- sovtoken/setup.py
> INDY-2200: Bump node version

- devops/Makefile
- sovtoken/setup.py
- sovtokenfees/sovtokenfees/test/3pc_batching/test_malicious_primary_sent_pp.py
- sovtokenfees/sovtokenfees/test/3pc_batching/test_malicious_primary_sent_pp_with_xfer.py
- sovtokenfees/sovtokenfees/test/test_get_fees_from_empty_state.py
- sovtokenfees/sovtokenfees/test/three_phase_commit_helper.py
- sovtokenfees/sovtokenfees/three_phase_commit_handling.py
> INDY-2211: bump indy-node version

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/test/req_handlers/mint_req_handler/test_mint_req_handler_dynamic_validation.py
> bump indy-node version

- devops/Makefile
- sovtoken/setup.py
> Bump indy-node version to 1.9.2~dev1067

- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [RC-1.0.2] bump packages version

- devops/Makefile
- sovtoken/setup.py
> [Stable-1.0.2] bump indy-node to stable version

- sovtoken/sovtoken/__metadata__.py
- sovtoken/sovtoken/metadata.json
- sovtokenfees/sovtokenfees/__metadata__.py
- sovtokenfees/sovtokenfees/metadata.json
> [ST-621] bump packages versions and try to change mode to 644

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/client_authnr.py
- sovtokenfees/sovtokenfees/test/test_client_authnr.py
Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>
> INDY-2103: Bump indy-node, indy-plenum versions

- devops/Makefile
- sovtoken/setup.py
> INDY-2183: bump node

- devops/Makefile
- sovtoken/setup.py
> [INDY-1336] bump indy-node version

- devops/build-scripts/xenial/sovtoken/postinst
- devops/build-scripts/xenial/sovtokenfees/postinst
> [ST-621] chmod 644 after install

- devops/Makefile
- sovtoken/setup.py
- sovtokenfees/sovtokenfees/test/catchup/revert/test_revert_fees.py
- sovtokenfees/sovtokenfees/test/three_phase_commit_helper.py
> INDY-2220: bump node version

- devops/docker/ci/xenial/Dockerfile
- sovtoken/setup.py
- sovtokenfees/setup.py
Signed-off-by: Vladimir Shishkin <vladimir.shishkin@dsr-corporation.com>
> bump client versions for sovrin pipeline

- devops/Makefile
- sovtoken/setup.py
> [INDY-2223] bump indy-node's version

- devops/Makefile
- sovtoken/setup.py
Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>
> INDY-2172: Bump node version

- devops/Makefile
- sovtoken/setup.py
Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>
> [INDY-2213]: Bump node version

- devops/Makefile
- sovtoken/setup.py
> [Stable-1.0.3] Bump indy-node to stable version

- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [NEW_RELEASE] bump to 1.0.4 devs release

- devops/Makefile
- sovtoken/setup.py
> INDY-2140: bump indy-node version

- devops/Makefile
- sovtoken/setup.py
> INDY-2140: Bump node version

- devops/Makefile
- sovtoken/setup.py
> [BUMP NODE] bump indy-node version

- devops/docker/ci/xenial/Dockerfile
- sovtoken/setup.py
- sovtokenfees/setup.py
> Bump libindy version

- devops/Makefile
- sovtoken/setup.py
Signed-off-by: Nemanja Patrnogic <patrnogicnemanja@gmail.com>
> [INDY-2235]: Bump node version

- devops/Makefile
- sovtoken/setup.py
> [Release-1.0.4] bump to stable indy-node

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [Future release] bump versions to new one

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/main.py
- sovtokenfees/sovtokenfees/test/three_phase_commit_helper.py
> bump indy-node

- devops/Makefile
- sovtoken/setup.py
> Bump node version

- devops/Makefile
- sovtoken/setup.py
> fix stashing of Checkpoint msgs during view change

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/main.py
- sovtoken/sovtoken/request_handlers/token_utils.py
- sovtoken/sovtoken/request_handlers/write_request_handler/xfer_handler_1_0_0.py
- sovtoken/sovtoken/test/req_handlers/xfer_req_handler/conftest.py
- sovtoken/sovtoken/test/req_handlers/xfer_req_handler/test_xfer_handler_1_0_0_update_state.py
- sovtoken/sovtoken/test/req_handlers/xfer_req_handler/test_xfer_handler_update_state.py
> INDY-2292: fix XFER for versions <=1.0.0

- devops/docker/ci/xenial/Dockerfile
- sovtokenfees/sovtokenfees/test/helper.py
- sovtokenfees/sovtokenfees/test/state_proof/test_get_fee_state_proof.py
- sovtokenfees/sovtokenfees/test/state_proof/test_get_fees_state_proof.py
- sovtokenfees/sovtokenfees/test/test_set_get_fees.py
> bump libsovtoken; fix tests for GET_FEES state proof

- devops/Makefile
- devops/docker/ci/xenial/Dockerfile
- sovtoken/setup.py
- sovtokenfees/sovtokenfees/test/catchup/test_leder_state_recovery_with_different_versions.py
- sovtokenfees/sovtokenfees/test/state_proof/test_get_fees_state_proof.py
> INDY-2292: restore state for token ledger

- sovtokenfees/sovtokenfees/test/state_proof/test_get_fees_state_proof.py
> Unskip test_state_proof_for_get_fees

- devops/Makefile
- sovtoken/setup.py
> [STABLE-1.0.5] Change indy-node dep to stable version

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [FUTURE_RELEASE] go to the new development cycle

- devops/Makefile
- sovtoken/setup.py
> [INDY-2303] Create first package for checking INDY-2303

- devops/Makefile
- sovtoken/setup.py
> [INDY-2303] Second package for check

- devops/Makefile
- sovtoken/setup.py
> INDY-2280: Bump node version

- devops/Makefile
- sovtoken/setup.py
> [INDY-2303] bump indy-node version

- devops/Makefile
- sovtoken/setup.py
> [INDY-2303] first package for test

- devops/Makefile
- sovtoken/setup.py
> [INDY-2303] The second package for testing

- devops/Makefile
- sovtoken/setup.py
> [INDY-2303] Make the third package for test

- devops/Makefile
- sovtoken/setup.py
> INDY-2313: Bump node version

- devops/Makefile
- sovtoken/setup.py
> INDY-2316: bump indy-node

- devops/Makefile
- sovtoken/setup.py
> INDY-2316: Bump node version

- devops/Makefile
- sovtoken/setup.py
> [STABLE-1.0.6] Change indy-node dep to stable version

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [FUTURE_RELEASE] bump version

- devops/docker/ci/xenial/Dockerfile
- sovtoken/setup.py
- sovtokenfees/setup.py
- sovtokenfees/sovtokenfees/fees_authorizer.py
- sovtokenfees/sovtokenfees/test/authorize/test_fees_authorizer.py
> [INDY-2221] drop log level to debug

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/main.py
- sovtokenfees/sovtokenfees/test/catchup/test_multiple_batches_for_pool.py
- sovtokenfees/sovtokenfees/test/catchup/test_revert_xfer_with_fees_before_catchup.py
- sovtokenfees/sovtokenfees/test/view_change/helper.py
- sovtokenfees/sovtokenfees/test/view_change/test_vc_reverting_batch.py
- sovtokenfees/sovtokenfees/test/view_change/test_vc_reverting_different_batches.py
> INDY-2322: bump node and fix tests

- devops/aws-codebuild/Jenkinsfile.cd
- devops/aws-codebuild/Jenkinsfile.ci
- sovtokenfees/sovtokenfees/test/catchup/revert/test_revert_fees.py
> [BUMP TIMEOUT] bump aws codebuild timeout

- devops/Makefile
- sovtoken/setup.py
> [INDY-2326] bump indy-node version

- devops/Makefile
- sovtoken/setup.py
> [1.0.7 stable] change deps to stable

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
> [FUTURE_RELEASE] new development circle

- devops/Makefile
- sovtoken/setup.py
Signed-off-by: Wade Barnes <wade.barnes@shaw.ca>
> [1.0.9 stable] change deps to stable

- Makefile
- README.md
- devops/denv/Dockerfile
- devops/docker/ci/xenial/Dockerfile
- devops/ext/docker/base/xenial/Dockerfile.0.1.0
- devops/ext/docker/base/xenial/Dockerfile.0.2.0
- docker-compose.yml
- install_payment_plugins.sh
- sovtoken/setup.py
1) remove unused config code
2) pin test dependencies
3) add missing test/dev dependencies
4) add wsl instructions.
Signed-off-by: Devin Smith <devinleighsmith@gmail.com>
> update token-plugin dev config:

- aws_local_codebuild.env
- codebuild_build.sh
- devops/Makefile
- devops/docker/ci/xenial/Dockerfile
- devops/ext/docker/base/xenial/Dockerfile.0.2.0
- sovtoken/setup.py
- sovtoken/sovtoken/request_handlers/write_request_handler/mint_handler.py
- sovtoken/sovtoken/request_handlers/write_request_handler/xfer_handler.py
- sovtokenfees/sovtokenfees/req_handlers/write_handlers/auth_rule_fee_handler.py
- sovtokenfees/sovtokenfees/req_handlers/write_handlers/auth_rules_fee_handler.py
- sovtokenfees/sovtokenfees/req_handlers/write_handlers/domain_fee_handler.py
- sovtokenfees/sovtokenfees/req_handlers/write_handlers/fee_txn_handler.py
- sovtokenfees/sovtokenfees/req_handlers/write_handlers/set_fees_handler.py
thanks to @Toktar for these changes. See #405 for original PR
> Up 41 set fees

- .github/workflows/build.yaml
- .github/workflows/build/Dockerfile.ubuntu-20-04
- devops/docker/ci/focal/Dockerfile
Signed-off-by: Devin Smith <devinleighsmith@gmail.com>
> bump consumed versions of plenum/node.

- .github/workflows/Push.yaml
- .github/workflows/publishRelease.yaml
- .github/workflows/reuseable_publish.yaml
> added ssh repo secret to publish WF

- .github/workflows/reuseable_publish.yaml
> fixed ssh directory

- .github/workflows/reuseable_publish.yaml
> fix missing folder

- .github/workflows/reuseable_publish.yaml
> decoupled commands for testing

- devops/Makefile
- devops/build-scripts/xenial/Pool_Party/Dockerfile
- devops/denv/Dockerfile
- devops/docker/cd/debs_upload.dockerfile
- devops/docker/ci/xenial/Dockerfile
- devops/ext/docker/base/xenial/Dockerfile.0.1.0
- devops/ext/docker/base/xenial/Dockerfile.0.2.0
- devops/ext/docker/python3/xenial/Dockerfile.0.1.0
- devops/vagrant/desktop/scripts/setup.sh
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> [RC-1.0.10] Release candidate for plugins

- devops/Makefile
- sovtoken/setup.py
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> [1.0.10 stable] change deps to stable

- devops/Makefile
- sovtoken/setup.py
- sovtoken/sovtoken/__metadata__.py
- sovtokenfees/sovtokenfees/__metadata__.py
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> [RC-1.0.11] Release candidate for plugins

- .github/workflows/Push.yaml
- .github/workflows/publishRelease.yaml
- .github/workflows/reuseable_publish.yaml
> fix pypi sovtoken and deb publishing

- .github/workflows/Push.yaml
> fixed typo in push.yaml

- .github/workflows/Push.yaml
- .github/workflows/reuseable_publish.yaml
> sovrin repo upload spec

- .devcontainer/Dockerfile
- .github/workflows/build/Dockerfile.ubuntu-2004
- .github/workflows/reuseable_build_package.yaml
- .github/workflows/reuseable_test.yaml
- .gitpod.Dockerfile
- .gitpod.yml
- install_payment_plugins.sh
- sovtoken/setup.py
- sovtokenfees/setup.py
> updated indy versions

- .github/workflows/reuseable_build_package.yaml
- devops/build-scripts/focal/sovtoken/postinst
- devops/build-scripts/focal/sovtokenfees/postinst
> postinst and prerm fixes

- .github/workflows/tag.yaml
- Following fix made here; https://github.com/sovrin-foundation/sovrin/pull/315
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> fixed correct checkout version & tags fetch

- .github/workflows/publishRelease.yaml
- .github/workflows/reuseable_build_package.yaml
> fix deb version build

- sovtoken/sovtoken/metadata.json
- sovtokenfees/sovtokenfees/metadata.json
[v1.1.0-rc0] - Update Version number for Release
> [v1.1.0-rc0] - Update Version Number for Release

- .github/workflows/publishRelease.yaml
- .github/workflows/repoDispatchable_updateNode.yaml
Automatically creates PR when token-plugin is triggered by node and triggers an update to sovrin, when a release is created.
> Repo Dispatch Node Update

- sovtoken/sovtoken/metadata.json
- sovtokenfees/sovtokenfees/metadata.json
[v1.1.0-rc1] - Update Version number for Release
> [v1.1.0-rc1] - Update Version Number for Release

- .github/workflows/publishRelease.yaml
- .github/workflows/repoDispatchable_updateNode.yaml
- .github/workflows/reuseable_publish.yaml
- .github/workflows/tag.yaml
> Upgrade to latest action versions

- sovtoken/sovtoken/metadata.json
- sovtokenfees/sovtokenfees/metadata.json
[v1.1.0] - Update Version number for Release
> [v1.1.0] - Update Version Number for Release

- sovtoken/sovtoken/metadata.json
- sovtokenfees/sovtokenfees/metadata.json
[v1.1.1] - Update Version number for Release
> [v1.1.1] - Update Version Number for Release
